-- Sample Word Pairs Data (Vietnamese)
-- Difficulty: 1 = Easy, 2 = Medium, 3 = Hard, 4 = Very Hard
-- Focus on Medium -> Hard (2-3) as per requirements
-- Total: 576 word pairs

-- Category: Abstract (53 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Tiết kiệm', 'Keo kiệt', 'abstract', 3),
('Thông minh', 'Khôn ngoan', 'abstract', 2),
('Dũng cảm', 'Can đảm', 'abstract', 2),
('Tốt bụng', 'Nhân hậu', 'abstract', 2),
('Thành công', 'Thắng lợi', 'abstract', 2),
('Thất bại', 'Thua cuộc', 'abstract', 2),
('Cơ hội', 'May mắn', 'abstract', 3),
('Thử thách', 'Khó khăn', 'abstract', 2),
('Mục tiêu', 'Mơ ước', 'abstract', 3),
('Giá trị', 'Ý nghĩa', 'abstract', 3),
('Tự do', 'Độc lập', 'abstract', 2),
('Công bằng', 'Công lý', 'abstract', 2),
('Tự ti', 'Nhút nhát', 'abstract', 2),
('Nóng vội', 'Vội vàng', 'abstract', 2),
('Bất cẩn', 'Thiếu cẩn thận', 'abstract', 2),
('Chăm chỉ', 'Siêng năng', 'abstract', 2),
('Lười biếng', 'Ỷ lại', 'abstract', 2),
('Ngu dốt', 'Kém thông minh', 'abstract', 2),
('Độc ác', 'Xấu xa', 'abstract', 2),
('Xấu', 'Tệ hại', 'abstract', 1),
('Sự thật', 'Chân lý', 'abstract', 2),
('Lý thuyết', 'Thực hành', 'abstract', 2),
('Kinh nghiệm', 'Trải nghiệm', 'abstract', 2),
('Văn hóa', 'Văn minh', 'abstract', 2),
('Pháp luật', 'Quy định', 'abstract', 2),
('Truyền thống', 'Phong tục', 'abstract', 2),
('Hiện đại', 'Tân tiến', 'abstract', 2),
('Cổ điển', 'Xưa cũ', 'abstract', 2),
('Đơn giản', 'Phức tạp', 'abstract', 1),
('Rõ ràng', 'Minh bạch', 'abstract', 2),
('Trách nhiệm', 'Nghĩa vụ', 'abstract', 2),
('Kiên nhẫn', 'Cố chấp', 'abstract', 3),
('Cẩn thận', 'Dè dặt', 'abstract', 2),
('Trung thực', 'Ngây thơ', 'abstract', 2),
('Dối trá', 'Khéo léo', 'abstract', 3),
('Đúng', 'Hợp lý', 'abstract', 2),
('Đẹp', 'Dễ thương', 'abstract', 1),
('Giả dối', 'Đạo đức giả', 'abstract', 3),
('Kiến thức', 'Thông tin', 'abstract', 2),
('Đạo đức', 'Pháp luật', 'abstract', 2),
('Tốt', 'Giỏi', 'abstract', 1),
('Sai', 'Lầm', 'abstract', 1),
('Lớn', 'Khổng lồ', 'abstract', 1),
('Nhỏ', 'Tí hon', 'abstract', 1),
('Cao', 'Dài', 'abstract', 1),
('Thấp', 'Ngắn', 'abstract', 1),
('Nhanh', 'Vội', 'abstract', 2),
('Chậm', 'Trễ', 'abstract', 2),
('Mới', 'Lạ', 'abstract', 1),
('Cũ', 'Cổ', 'abstract', 1),
('Dễ', 'Đơn giản', 'abstract', 1),
('Thông minh', 'Sáng tạo', 'abstract', 2),
('Thành công', 'Hạnh phúc', 'abstract', 2);

-- Category: Actions (52 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Hẹn hò', 'Tán tỉnh', 'actions', 3),
('Đi bộ', 'Chạy bộ', 'actions', 2),
('Ngủ', 'Nghỉ ngơi', 'actions', 2),
('Ăn', 'Uống', 'actions', 1),
('Học', 'Làm bài', 'actions', 2),
('Chơi game', 'Giải trí', 'actions', 2),
('Xem phim', 'Xem TV', 'actions', 2),
('Đọc sách', 'Đọc báo', 'actions', 2),
('Nấu ăn', 'Chuẩn bị đồ ăn', 'actions', 2),
('Dọn dẹp', 'Vệ sinh', 'actions', 2),
('Đánh răng', 'Vệ sinh răng', 'actions', 1),
('Đi xe', 'Lái xe', 'actions', 2),
('Chạy', 'Tập thể dục', 'actions', 2),
('Nhảy', 'Khiêu vũ', 'actions', 2),
('Chơi nhạc', 'Chơi đàn', 'actions', 2),
('Vẽ', 'Tô màu', 'actions', 2),
('Viết', 'Ghi chép', 'actions', 2),
('Đọc', 'Xem', 'actions', 1),
('Nghe', 'Lắng nghe', 'actions', 2),
('Nói', 'Phát biểu', 'actions', 2),
('Hỏi', 'Thắc mắc', 'actions', 2),
('Giải thích', 'Làm rõ', 'actions', 2),
('Thảo luận', 'Bàn luận', 'actions', 2),
('Hòa giải', 'Giải quyết', 'actions', 2),
('Thỏa thuận', 'Đồng ý', 'actions', 2),
('Từ bỏ', 'Bỏ cuộc', 'actions', 2),
('Tiếp tục', 'Duy trì', 'actions', 2),
('Bắt đầu', 'Khởi động', 'actions', 2),
('Kết thúc', 'Hoàn thành', 'actions', 2),
('Làm việc', 'Công việc', 'actions', 2),
('Học tập', 'Nghiên cứu', 'actions', 2),
('Du lịch', 'Đi chơi', 'actions', 2),
('Ngáp', 'Hắt hơi', 'actions', 1),
('Cười', 'Khóc', 'actions', 1),
('La hét', 'Thì thầm', 'actions', 2),
('Ôm', 'Hôn', 'actions', 1),
('Nằm', 'Ngồi', 'actions', 1),
('Đứng', 'Quỳ', 'actions', 1),
('Tắm', 'Gội đầu', 'actions', 1),
('Mặc đồ', 'Trang điểm', 'actions', 2),
('Hát', 'Đọc rap', 'actions', 2),
('Trả lời', 'Phản biện', 'actions', 3),
('Tranh cãi', 'Thảo luận', 'actions', 2),
('Từ chối', 'Trì hoãn', 'actions', 2),
('Dừng lại', 'Quay lại', 'actions', 2),
('Thăm hỏi', 'Tặng quà', 'actions', 2),
('Gặp gỡ', 'Hẹn hò', 'actions', 2),
('Chia tay', 'Ly hôn', 'actions', 3),
('Cấu', 'Tát', 'actions', 2),
('Nói chuyện', 'Phỏng vấn', 'actions', 2),
('Đi bộ', 'Leo cầu thang', 'actions', 2),
('Ngủ', 'Chợp mắt', 'actions', 2);

-- Category: Animals (55 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Chó', 'Mèo', 'animals', 1),
('Bò', 'Trâu', 'animals', 2),
('Ngựa', 'Lừa', 'animals', 2),
('Dê', 'Cừu', 'animals', 2),
('Thỏ', 'Chuột', 'animals', 2),
('Tôm', 'Cua', 'animals', 2),
('Sư tử', 'Hổ', 'animals', 2),
('Gấu', 'Báo', 'animals', 2),
('Voi', 'Hươu', 'animals', 2),
('Khỉ', 'Vượn', 'animals', 2),
('Rắn', 'Rồng', 'animals', 2),
('Cá sấu', 'Rùa', 'animals', 2),
('Chim cánh cụt', 'Gấu trúc', 'animals', 2),
('Kangaroo', 'Koala', 'animals', 2),
('Cá heo', 'Cá voi', 'animals', 2),
('Bướm', 'Ong', 'animals', 2),
('Kiến', 'Mối', 'animals', 2),
('Nhện', 'Bọ cạp', 'animals', 2),
('Gián', 'Muỗi', 'animals', 2),
('Chim sẻ', 'Chim bồ câu', 'animals', 2),
('Chim đại bàng', 'Chim ưng', 'animals', 2),
('Nhím', 'Chuột chũi', 'animals', 2),
('Hà mã', 'Tê giác', 'animals', 2),
('Sao biển', 'Cầu gai', 'animals', 2),
('Hải cẩu', 'Sư tử biển', 'animals', 2),
('Đại bàng', 'Kền kền', 'animals', 2),
('Cú mèo', 'Diều hâu', 'animals', 2),
('Bồ nông', 'Hạc', 'animals', 2),
('Thiên nga', 'Ngỗng trời', 'animals', 2),
('Rái cá', 'Hải ly', 'animals', 2),
('Chồn', 'Cầy hương', 'animals', 2),
('Dơi', 'Chim', 'animals', 1),
('Cá voi xanh', 'Cá nhà táng', 'animals', 2),
('Cá kiếm', 'Cá ngừ', 'animals', 2),
('Tôm hùm', 'Cua hoàng đế', 'animals', 2),
('Ốc', 'Sò', 'animals', 1),
('Hến', 'Trai', 'animals', 2),
('Ve sầu', 'Dế', 'animals', 2),
('Bọ ngựa', 'Châu chấu', 'animals', 2),
('Chuồn chuồn', 'Bướm đêm', 'animals', 2),
('Rết', 'Cuốn chiếu', 'animals', 2),
('Bọ hung', 'Bọ cánh cứng', 'animals', 2),
('Ếch', 'Cóc', 'animals', 1),
('Nhái', 'Ễnh ương', 'animals', 2),
('Thằn lằn', 'Tắc kè', 'animals', 2),
('Kỳ đà', 'Kỳ nhông', 'animals', 2),
('Phượng hoàng', 'Công', 'animals', 2),
('Sói', 'Cáo', 'animals', 2),
('Hươu cao cổ', 'Đà điểu', 'animals', 2),
('Lợn', 'Lợn rừng', 'animals', 2),
('Vịt', 'Ngan', 'animals', 2),
('Sứa', 'Mực', 'animals', 2),
('Cá sấu', 'Thằn lằn', 'animals', 2),
('Hổ', 'Báo', 'animals', 2),
('Sư tử', 'Sư tử biển', 'animals', 3);

-- Category: Body (50 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Đầu', 'Não', 'body', 2),
('Mắt', 'Mũi', 'body', 1),
('Miệng', 'Môi', 'body', 2),
('Răng', 'Lưỡi', 'body', 2),
('Tay', 'Chân', 'body', 1),
('Ngón tay', 'Ngón chân', 'body', 2),
('Cổ', 'Vai', 'body', 2),
('Lưng', 'Ngực', 'body', 2),
('Tim', 'Phổi', 'body', 2),
('Gan', 'Thận', 'body', 2),
('Xương', 'Cơ', 'body', 2),
('Da', 'Tóc', 'body', 1),
('Móng tay', 'Móng chân', 'body', 2),
('Lông mày', 'Lông mi', 'body', 2),
('Má', 'Cằm', 'body', 2),
('Trán', 'Thái dương', 'body', 2),
('Cổ họng', 'Thanh quản', 'body', 2),
('Đau bụng', 'Đau dạ dày', 'body', 2),
('Sốt', 'Cảm', 'body', 2),
('Ho', 'Sổ mũi', 'body', 2),
('Khỏe mạnh', 'Cường tráng', 'body', 2),
('Ốm yếu', 'Bệnh tật', 'body', 2),
('Bác sĩ', 'Y tá', 'body', 2),
('Khám bệnh', 'Điều trị', 'body', 2),
('Tiêm', 'Uống thuốc', 'body', 2),
('Băng bó', 'Băng gạc', 'body', 2),
('Vết thương', 'Vết cắt', 'body', 2),
('Máu', 'Huyết', 'body', 1),
('Nhịp tim', 'Huyết áp', 'body', 2),
('Hô hấp', 'Thở', 'body', 2),
('Tiêu hóa', 'Hấp thụ', 'body', 2),
('Miễn dịch', 'Kháng thể', 'body', 2),
('Dị ứng', 'Phản ứng', 'body', 2),
('Viêm', 'Sưng', 'body', 2),
('Nhiễm trùng', 'Nhiễm khuẩn', 'body', 2),
('Vaccine', 'Tiêm chủng', 'body', 2),
('Phòng ngừa', 'Phòng bệnh', 'body', 2),
('Ruột', 'Dạ dày', 'body', 2),
('Mật', 'Tụy', 'body', 3),
('Tử cung', 'Buồng trứng', 'body', 3),
('Tinh hoàn', 'Tuyến tiền liệt', 'body', 3),
('Huyết tương', 'Huyết cầu', 'body', 3),
('Bạch cầu', 'Hồng cầu', 'body', 2),
('Tiểu cầu', 'Huyết sắc tố', 'body', 3),
('Đau đầu', 'Chóng mặt', 'body', 2),
('Thuốc tây', 'Thuốc nam', 'body', 2),
('Hồi phục', 'Tăng cường', 'body', 2),
('Khỏi bệnh', 'Miễn dịch', 'body', 3),
('Phẫu thuật', 'Tiểu phẫu', 'body', 2),
('Xăm', 'Châm cứu', 'body', 2);

-- Category: Colors (48 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Đỏ', 'Hồng', 'colors', 2),
('Xanh', 'Tím', 'colors', 2),
('Vàng', 'Cam', 'colors', 2),
('Trắng', 'Xám', 'colors', 2),
('Đen', 'Nâu', 'colors', 2),
('Xanh lá', 'Xanh dương', 'colors', 2),
('Đỏ đậm', 'Đỏ nhạt', 'colors', 2),
('Xanh đậm', 'Xanh nhạt', 'colors', 2),
('Vàng đậm', 'Vàng nhạt', 'colors', 2),
('Hồng đậm', 'Hồng nhạt', 'colors', 2),
('Tím đậm', 'Tím nhạt', 'colors', 2),
('Cam đậm', 'Cam nhạt', 'colors', 2),
('Nâu đậm', 'Nâu nhạt', 'colors', 2),
('Xám đậm', 'Xám nhạt', 'colors', 2),
('Đục', 'Mờ', 'colors', 1),
('Màu trung tính', 'Màu trung tính', 'colors', 1),
('Pastel', 'Màu pastel', 'colors', 1),
('Neon', 'Màu neon', 'colors', 1),
('Metallic', 'Màu kim loại', 'colors', 1),
('Gradient', 'Chuyển màu', 'colors', 1),
('Monochrome', 'Đơn sắc', 'colors', 1),
('Rainbow', 'Cầu vồng', 'colors', 1),
('Ivory', 'Ngà voi', 'colors', 2),
('Turquoise', 'Ngọc lam', 'colors', 2),
('Magenta', 'Đỏ tía', 'colors', 2),
('Cyan', 'Xanh lơ', 'colors', 2),
('Maroon', 'Nâu đỏ', 'colors', 2),
('Navy', 'Xanh navy', 'colors', 2),
('Olive', 'Ô liu', 'colors', 2),
('Salmon', 'Cá hồi', 'colors', 2),
('Lavender', 'Oải hương', 'colors', 2),
('Màu da', 'Màu nude', 'colors', 2),
('Màu đất', 'Màu gạch', 'colors', 2),
('Màu rêu', 'Màu cỏ úa', 'colors', 2),
('Màu khói', 'Màu ghi', 'colors', 2),
('Màu bạc', 'Màu xám', 'colors', 2),
('Màu đồng', 'Màu vàng đồng', 'colors', 2),
('Màu than', 'Màu chì', 'colors', 2),
('Màu mận', 'Màu bordeaux', 'colors', 2),
('Màu chàm', 'Màu lam', 'colors', 2),
('Màu kem', 'Màu sữa', 'colors', 2),
('Màu nước', 'Màu sáp', 'colors', 2),
('Dạ quang', 'Phản quang', 'colors', 2),
('Trong suốt', 'Vô hình', 'colors', 3),
('Màu nóng', 'Màu sặc sỡ', 'colors', 2),
('Màu lạnh', 'Màu trầm', 'colors', 2),
('Đen', 'Xám tro', 'colors', 2),
('Trắng', 'Kem', 'colors', 2);

-- Category: Emotions (49 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Yêu', 'Thích', 'emotions', 3),
('Ghen', 'Đố kỵ', 'emotions', 3),
('Vui', 'Hạnh phúc', 'emotions', 2),
('Buồn', 'Thất vọng', 'emotions', 2),
('Tức giận', 'Bực bội', 'emotions', 2),
('Lo lắng', 'Sợ hãi', 'emotions', 3),
('Tự tin', 'Kiêu ngạo', 'emotions', 3),
('Nhớ', 'Thương', 'emotions', 3),
('Hồi hộp', 'Lo âu', 'emotions', 3),
('Đau khổ', 'Buồn bã', 'emotions', 2),
('Tự hào', 'Kiêu hãnh', 'emotions', 3),
('Chán nản', 'Mệt mỏi', 'emotions', 2),
('Bình tĩnh', 'Thư thái', 'emotions', 2),
('Căng thẳng', 'Áp lực', 'emotions', 2),
('Thương hại', 'Đồng cảm', 'emotions', 3),
('Tha thứ', 'Bỏ qua', 'emotions', 2),
('Oán giận', 'Thù hận', 'emotions', 2),
('Yêu thương', 'Quý mến', 'emotions', 2),
('Ghét bỏ', 'Không thích', 'emotions', 2),
('Hy vọng', 'Mong đợi', 'emotions', 2),
('Lạc quan', 'Tích cực', 'emotions', 2),
('Bi quan', 'Tiêu cực', 'emotions', 2),
('Đau đớn', 'Khổ sở', 'emotions', 2),
('Tuyệt vời', 'Hoàn hảo', 'emotions', 2),
('Tồi tệ', 'Kinh khủng', 'emotions', 2),
('Mê', 'Nghiện', 'emotions', 1),
('Ghét', 'Căm', 'emotions', 2),
('Có lỗi', 'Ân hận', 'emotions', 2),
('Hối hận', 'Tiếc nuối', 'emotions', 2),
('Ngạc nhiên', 'Sợ hãi', 'emotions', 2),
('Xấu hổ', 'Tự ti', 'emotions', 2),
('Thích thú', 'Tò mò', 'emotions', 2),
('Phấn khích', 'Hồi hộp', 'emotions', 2),
('Thoải mái', 'Lười biếng', 'emotions', 2),
('Khó chịu', 'Đau đớn', 'emotions', 2),
('Hài lòng', 'Thỏa mãn', 'emotions', 2),
('Bất mãn', 'Ghen tị', 'emotions', 2),
('Biết ơn', 'Nợ nần', 'emotions', 3),
('Kính trọng', 'Sợ sệt', 'emotions', 3),
('Khinh thường', 'Thương hại', 'emotions', 3),
('Ngưỡng mộ', 'Ghen tị', 'emotions', 3),
('Tuyệt vọng', 'Buông xuôi', 'emotions', 2),
('Bối rối', 'Hoảng loạn', 'emotions', 2),
('Ngại ngùng', 'Giữ kẽ', 'emotions', 2),
('Phấn khởi', 'Lạc quan', 'emotions', 2),
('Chán', 'Ghét', 'emotions', 1),
('Thù', 'Giận', 'emotions', 1),
('Cô đơn', 'Yên tĩnh', 'emotions', 2),
('Vui sướng', 'Hả hê', 'emotions', 2);

-- Category: Food (56 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Trà sữa', 'Trà đào', 'food', 2),
('Cà phê', 'Cà phê sữa', 'food', 2),
('Bánh mì', 'Bánh bao', 'food', 2),
('Phở', 'Bún bò', 'food', 2),
('Gỏi cuốn', 'Chả giò', 'food', 3),
('Bánh xèo', 'Bánh khọt', 'food', 3),
('Nước mắm', 'Nước tương', 'food', 2),
('Cơm', 'Xôi', 'food', 2),
('Chè', 'Sữa chua', 'food', 2),
('Bánh chưng', 'Bánh tét', 'food', 3),
('Nem', 'Chả', 'food', 2),
('Cháo', 'Súp', 'food', 2),
('Nước ngọt', 'Nước ép', 'food', 2),
('Bia', 'Rượu', 'food', 2),
('Sữa', 'Sữa đậu nành', 'food', 2),
('Kẹo', 'Socola', 'food', 2),
('Bánh mì kẹp', 'Bánh mì sandwich', 'food', 1),
('Sushi', 'Cơm cuộn', 'food', 2),
('Salad', 'Gỏi', 'food', 2),
('Steak', 'Thịt bò', 'food', 2),
('Bún riêu', 'Bún ốc', 'food', 2),
('Bún chả', 'Bún thịt nướng', 'food', 2),
('Cơm tấm', 'Cơm sườn', 'food', 2),
('Cháo lòng', 'Cháo gà', 'food', 2),
('Lẩu', 'Nướng', 'food', 1),
('Rượu vang', 'Champagne', 'food', 2),
('Cocktail', 'Mocktail', 'food', 2),
('Trà đá', 'Nhân trần', 'food', 2),
('Bánh tráng trộn', 'Bánh tráng nướng', 'food', 2),
('Xoài lắc', 'Cóc lắc', 'food', 2),
('Bò khô', 'Khô gà', 'food', 2),
('Mực rim', 'Cá rim', 'food', 2),
('Bánh cuốn', 'Bánh ướt', 'food', 2),
('Nem chua', 'Chả lụa', 'food', 2),
('Gà rán', 'Gà luộc', 'food', 2),
('Cá kho', 'Cá hấp', 'food', 2),
('Thịt kho', 'Thịt luộc', 'food', 2),
('Mì Ý', 'Nui', 'food', 2),
('Trứng ốp la', 'Trứng luộc', 'food', 2),
('Phô mai', 'Bơ', 'food', 2),
('Đường', 'Mật ong', 'food', 2),
('Muối', 'Nước mắm', 'food', 2),
('Tiêu', 'Ớt', 'food', 2),
('Tỏi', 'Hành tím', 'food', 2),
('Hành tây', 'Hành ta', 'food', 2),
('Cà chua', 'Dưa leo', 'food', 2),
('Khoai tây', 'Khoai lang', 'food', 2),
('Cà rốt', 'Củ cải trắng', 'food', 2),
('Chuối', 'Táo', 'food', 1),
('Hamburger', 'Sandwich', 'food', 2),
('Bánh quy', 'Bánh xốp', 'food', 2),
('Mì tôm', 'Phở gói', 'food', 2),
('Bánh kem', 'Bánh bông lan', 'food', 2),
('Buffet', 'Gọi món', 'food', 2),
('Lẩu thái', 'Lẩu hải sản', 'food', 2),
('Nướng BBQ', 'Nướng ngói', 'food', 2);

-- Category: Places (53 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Nhà', 'Căn hộ', 'places', 2),
('Trường học', 'Đại học', 'places', 2),
('Bệnh viện', 'Phòng khám', 'places', 2),
('Siêu thị', 'Cửa hàng', 'places', 2),
('Nhà hàng', 'Quán ăn', 'places', 2),
('Công viên', 'Sân chơi', 'places', 2),
('Bãi biển', 'Hồ bơi', 'places', 2),
('Rạp chiếu phim', 'Rạp hát', 'places', 2),
('Sân bay', 'Ga tàu', 'places', 2),
('Thành phố', 'Thị trấn', 'places', 2),
('Quán cà phê', 'Quán trà', 'places', 2),
('Thư viện', 'Phòng đọc', 'places', 2),
('Bảo tàng', 'Phòng trưng bày', 'places', 2),
('Nhà ga', 'Bến xe', 'places', 2),
('Bến tàu', 'Cảng', 'places', 2),
('Quán bar', 'Quán rượu', 'places', 2),
('Khách sạn', 'Nhà nghỉ', 'places', 2),
('Trung tâm mua sắm', 'Chợ', 'places', 2),
('Ngân hàng', 'Quỹ tín dụng', 'places', 2),
('Trạm dừng', 'Bến xe buýt', 'places', 2),
('Trường mẫu giáo', 'Trường tiểu học', 'places', 2),
('Trường cấp 2', 'Trường cấp 3', 'places', 2),
('Sân thượng', 'Ban công', 'places', 2),
('Sân sau', 'Vườn sau', 'places', 2),
('Hành lang', 'Lối đi', 'places', 2),
('Cầu thang', 'Thang máy', 'places', 2),
('Tòa án', 'Viện kiểm sát', 'places', 2),
('Ủy ban', 'Cơ quan', 'places', 2),
('Lăng tẩm', 'Đền đài', 'places', 2),
('Chùa', 'Đình', 'places', 2),
('Tu viện', 'Thiền viện', 'places', 2),
('Rừng', 'Núi', 'places', 1),
('Công viên', 'Vườn hoa', 'places', 2),
('Sân vận động', 'Nhà thi đấu', 'places', 2),
('Phòng gym', 'Sân tập', 'places', 2),
('Bưu điện', 'Ngân hàng', 'places', 2),
('Trạm xăng', 'Trạm thu phí', 'places', 2),
('Phòng học', 'Thư viện', 'places', 2),
('Phòng thí nghiệm', 'Phòng mổ', 'places', 3),
('Phòng họp', 'Hội trường', 'places', 2),
('Văn phòng', 'Phòng làm việc', 'places', 1),
('Nhà xưởng', 'Nhà máy', 'places', 2),
('Kho', 'Hầm', 'places', 2),
('Garage', 'Bãi xe', 'places', 2),
('Lối vào', 'Cổng', 'places', 1),
('Lối ra', 'Thoát hiểm', 'places', 2),
('Tầng 1', 'Sảnh', 'places', 2),
('Tầng thượng', 'Gác mái', 'places', 2),
('Tầng hầm', 'Hầm mỏ', 'places', 3),
('Nhà tù', 'Đảo hoang', 'places', 3),
('Đồn cảnh sát', 'Tòa án', 'places', 2),
('Nhà thờ', 'Chùa', 'places', 2),
('Sở thú', 'Rạp xiếc', 'places', 2);

-- Category: Sports (52 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Bóng đá', 'Bóng rổ', 'sports', 2),
('Bóng chuyền', 'Bóng bàn', 'sports', 2),
('Cầu lông', 'Tennis', 'sports', 2),
('Ném', 'Ném bóng', 'sports', 2),
('Đá', 'Đá bóng', 'sports', 1),
('Đánh', 'Đánh bóng', 'sports', 1),
('Bắt', 'Bắt bóng', 'sports', 1),
('Bắn', 'Bắn cung', 'sports', 2),
('Leo', 'Leo núi', 'sports', 2),
('Lặn', 'Lặn biển', 'sports', 2),
('Lướt', 'Lướt sóng', 'sports', 2),
('Trượt', 'Trượt tuyết', 'sports', 2),
('Đua', 'Đua xe', 'sports', 2),
('Vận động viên', 'Cầu thủ', 'sports', 2),
('Trọng tài', 'Huấn luyện viên', 'sports', 2),
('Sân thi đấu', 'Sân tập', 'sports', 2),
('Giải đấu', 'Cuộc thi', 'sports', 2),
('Trận đấu', 'Trận thi đấu', 'sports', 2),
('Thắng', 'Thua', 'sports', 1),
('Ghi bàn', 'Ghi điểm', 'sports', 2),
('Bàn thắng', 'Điểm số', 'sports', 2),
('Thẻ vàng', 'Thẻ đỏ', 'sports', 2),
('Thời gian', 'Hiệp', 'sports', 2),
('Vòng', 'Trận', 'sports', 2),
('Giải', 'Cúp', 'sports', 2),
('Huy chương vàng', 'Huy chương bạc', 'sports', 2),
('Kỷ lục', 'Thành tích', 'sports', 2),
('Thể lực', 'Sức khỏe', 'sports', 2),
('Golf', 'Khúc côn cầu', 'sports', 2),
('Bi-a', 'Bowling', 'sports', 2),
('Cờ vua', 'Cờ tướng', 'sports', 2),
('Cờ vây', 'Cờ caro', 'sports', 2),
('Đấu kiếm', 'Đấu vật', 'sports', 2),
('Judo', 'Karate', 'sports', 2),
('Taekwondo', 'Vovinam', 'sports', 2),
('Boxing', 'Quyền anh', 'sports', 1),
('Muay Thái', 'Kickboxing', 'sports', 2),
('Thể dục dụng cụ', 'Nhào lộn', 'sports', 2),
('Trượt băng', 'Patin', 'sports', 2),
('Đua ngựa', 'Đua chó', 'sports', 2),
('Đua thuyền', 'Chèo thuyền', 'sports', 2),
('Nhảy dù', 'Dù lượn', 'sports', 2),
('Cắm trại', 'Dã ngoại', 'sports', 2),
('Yoga', 'Thiền', 'sports', 2),
('Aerobic', 'Zumba', 'sports', 2),
('Marathon', 'Triathlon', 'sports', 2),
('Parkour', 'Freerunning', 'sports', 3),
('Esport', 'Game', 'sports', 2),
('Phạm lỗi', 'Việt vị', 'sports', 2),
('Tập luyện', 'Thi đấu', 'sports', 2),
('Bóng đá', 'Bóng đá trong nhà', 'sports', 2),
('Bơi', 'Lặn', 'sports', 2);

-- Category: Tech (62 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Grab', 'Be', 'tech', 2),
('Facebook', 'Instagram', 'tech', 2),
('iPhone', 'Samsung', 'tech', 2),
('Streaming', 'Xem trực tuyến', 'tech', 2),
('Flex', 'Khoe khoang', 'tech', 2),
('Trap boy', 'Bad boy', 'tech', 2),
('TikTok', 'YouTube', 'tech', 2),
('WhatsApp', 'Messenger', 'tech', 2),
('Zoom', 'Google Meet', 'tech', 2),
('Netflix', 'Disney+', 'tech', 2),
('Spotify', 'Apple Music', 'tech', 2),
('Airbnb', 'Booking', 'tech', 2),
('Amazon', 'Shopee', 'tech', 2),
('PayPal', 'Momo', 'tech', 2),
('Bitcoin', 'Tiền điện tử', 'tech', 2),
('NFT', 'Token', 'tech', 2),
('Bluetooth', 'NFC', 'tech', 2),
('Loa', 'Tai nghe', 'tech', 1),
('Màn hình', 'Máy chiếu', 'tech', 2),
('Pin', 'Sạc', 'tech', 1),
('iOS', 'Android', 'tech', 2),
('Windows', 'MacOS', 'tech', 2),
('Chrome', 'Firefox', 'tech', 2),
('Word', 'Excel', 'tech', 1),
('Photoshop', 'Canva', 'tech', 2),
('Mp3', 'Mp4', 'tech', 1),
('Jpg', 'Png', 'tech', 2),
('Usb', 'Thẻ nhớ', 'tech', 1),
('Modem', 'Router', 'tech', 2),
('Ram', 'Rom', 'tech', 2),
('Ssd', 'Hdd', 'tech', 2),
('Fanpage', 'Group', 'tech', 2),
('Block', 'Report', 'tech', 2),
('Inbox', 'Comment', 'tech', 1),
('Livestream', 'Story', 'tech', 2),
('Filter', 'Effect', 'tech', 2),
('Hashtag', 'Tag', 'tech', 2),
('Admin', 'Mod', 'tech', 2),
('Member', 'Follower', 'tech', 2),
('Online', 'Offline', 'tech', 1),
('Login', 'Logout', 'tech', 1),
('Sign up', 'Sign in', 'tech', 2),
('Copy', 'Cut', 'tech', 1),
('Undo', 'Redo', 'tech', 2),
('Save', 'Export', 'tech', 2),
('Click', 'Touch', 'tech', 1),
('Swipe', 'Scroll', 'tech', 2),
('Zoom in', 'Zoom out', 'tech', 1),
('Mute', 'Unmute', 'tech', 1),
('Play', 'Pause', 'tech', 1),
('Wifi', '4G', 'tech', 1),
('Spam', 'Quảng cáo', 'tech', 2),
('Glitch', 'Lag', 'tech', 2),
('Trojan', 'Worm', 'tech', 3),
('Nickname', 'Realname', 'tech', 2),
('Emoji', 'Sticker', 'tech', 1),
('Review', 'Feedback', 'tech', 2),
('Client', 'Host', 'tech', 3),
('Python', 'Java', 'tech', 2),
('Logic', 'Syntax', 'tech', 3),
('Mining', 'Staking', 'tech', 3),
('Ví điện tử', 'Tài khoản ngân hàng', 'tech', 2);

-- Category: Time (46 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Sáng', 'Trưa', 'time', 2),
('Chiều', 'Tối', 'time', 2),
('Hôm nay', 'Hôm qua', 'time', 2),
('Tuần', 'Tháng', 'time', 2),
('Năm', 'Thập kỷ', 'time', 2),
('Giờ', 'Phút', 'time', 1),
('Xuân', 'Hạ', 'time', 2),
('Thu', 'Đông', 'time', 2),
('Thứ Hai', 'Thứ Ba', 'time', 2),
('Thứ Tư', 'Thứ Năm', 'time', 2),
('Thứ Sáu', 'Thứ Bảy', 'time', 2),
('Quá khứ', 'Hiện tại', 'time', 2),
('Trước', 'Sau', 'time', 1),
('Sớm', 'Muộn', 'time', 1),
('Luôn luôn', 'Thường xuyên', 'time', 2),
('Thỉnh thoảng', 'Hiếm khi', 'time', 2),
('Tạm thời', 'Tạm bợ', 'time', 2),
('Ngắn hạn', 'Dài hạn', 'time', 2),
('Thế kỷ', 'Thiên niên kỷ', 'time', 2),
('Quý', 'Học kỳ', 'time', 2),
('Đầu tuần', 'Cuối tuần', 'time', 1),
('Mùa mưa', 'Mùa khô', 'time', 1),
('Mùa gặt', 'Mùa cấy', 'time', 2),
('Tết', 'Lễ', 'time', 1),
('Sinh nhật', 'Thôi nôi', 'time', 2),
('Giỗ', 'Kỷ niệm', 'time', 2),
('Đồng hồ', 'Lịch', 'time', 1),
('Noel', 'Tết Dương lịch', 'time', 2),
('Bình minh', 'Hoàng hôn', 'time', 1),
('Đêm', 'Tối', 'time', 1),
('Trưa', 'Chiều', 'time', 1),
('Mãi mãi', 'Lâu dài', 'time', 2),
('Mùa vụ', 'Thời vụ', 'time', 2),
('Sớm mai', 'Đêm khuya', 'time', 2),
('Tích tắc', 'Thập kỷ', 'time', 3),
('Vĩnh cửu', 'Thoáng qua', 'time', 3),
('Khoảnh khắc', 'Kỷ niệm', 'time', 2),
('Thời đại', 'Thế hệ', 'time', 2),
('Thanh xuân', 'Tuổi thơ', 'time', 2),
('Tuổi già', 'Tuổi thọ', 'time', 2),
('Tương lai', 'Viễn cảnh', 'time', 2),
('Hôm kia', 'Tuần trước', 'time', 2),
('Ngày mốt', 'Tuần sau', 'time', 2),
('Đám cưới', 'Đính hôn', 'time', 2),
('Đám ma', 'Giỗ đầu', 'time', 2),
('Đồng hồ', 'La bàn', 'time', 2);

-- Total: 576 word pairs
