-- Sample Word Pairs Data (Vietnamese)
-- Difficulty: 1 = Easy, 2 = Medium, 3 = Hard, 4 = Very Hard
-- Focus on Medium -> Hard (2-3) as per requirements
-- Total: 508 word pairs

-- Category: Trừu tượng (53 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Tiết kiệm', 'Keo kiệt', 'Trừu tượng', 3),
('Thông minh', 'Khôn ngoan', 'Trừu tượng', 2),
('Dũng cảm', 'Can đảm', 'Trừu tượng', 2),
('Tốt bụng', 'Nhân hậu', 'Trừu tượng', 2),
('Thành công', 'Thắng lợi', 'Trừu tượng', 2),
('Thất bại', 'Thua cuộc', 'Trừu tượng', 2),
('Cơ hội', 'May mắn', 'Trừu tượng', 3),
('Thử thách', 'Khó khăn', 'Trừu tượng', 2),
('Mục tiêu', 'Mơ ước', 'Trừu tượng', 3),
('Giá trị', 'Ý nghĩa', 'Trừu tượng', 3),
('Tự do', 'Độc lập', 'Trừu tượng', 2),
('Công bằng', 'Công lý', 'Trừu tượng', 2),
('Tự ti', 'Nhút nhát', 'Trừu tượng', 2),
('Nóng vội', 'Vội vàng', 'Trừu tượng', 2),
('Bất cẩn', 'Thiếu cẩn thận', 'Trừu tượng', 2),
('Chăm chỉ', 'Siêng năng', 'Trừu tượng', 2),
('Lười biếng', 'Ỷ lại', 'Trừu tượng', 2),
('Ngu dốt', 'Kém thông minh', 'Trừu tượng', 2),
('Độc ác', 'Xấu xa', 'Trừu tượng', 2),
('Xấu', 'Tệ hại', 'Trừu tượng', 1),
('Sự thật', 'Chân lý', 'Trừu tượng', 2),
('Lý thuyết', 'Học thuyết', 'Trừu tượng', 2),
('Kinh nghiệm', 'Trải nghiệm', 'Trừu tượng', 2),
('Văn hóa', 'Văn minh', 'Trừu tượng', 2),
('Pháp luật', 'Quy định', 'Trừu tượng', 2),
('Truyền thống', 'Phong tục', 'Trừu tượng', 2),
('Hiện đại', 'Tân tiến', 'Trừu tượng', 2),
('Cổ điển', 'Xưa cũ', 'Trừu tượng', 2),
('Đơn giản', 'Dễ hiểu', 'Trừu tượng', 1),
('Rõ ràng', 'Minh bạch', 'Trừu tượng', 2),
('Trách nhiệm', 'Nghĩa vụ', 'Trừu tượng', 2),
('Kiên nhẫn', 'Nhẫn nại', 'Trừu tượng', 3),
('Cẩn thận', 'Dè dặt', 'Trừu tượng', 2),
('Trung thực', 'Thật thà', 'Trừu tượng', 2),
('Dối trá', 'Gian dối', 'Trừu tượng', 3),
('Đúng', 'Hợp lý', 'Trừu tượng', 2),
('Đẹp', 'Dễ thương', 'Trừu tượng', 1),
('Giả dối', 'Đạo đức giả', 'Trừu tượng', 3),
('Kiến thức', 'Thông tin', 'Trừu tượng', 2),
('Đạo đức', 'Luân lý', 'Trừu tượng', 2),
('Tốt', 'Tử tế', 'Trừu tượng', 1),
('Sai', 'Lầm', 'Trừu tượng', 1),
('Lớn', 'Khổng lồ', 'Trừu tượng', 1),
('Nhỏ', 'Tí hon', 'Trừu tượng', 1),
('Cao', 'Cao ráo', 'Trừu tượng', 1),
('Thấp', 'Ngắn', 'Trừu tượng', 1),
('Nhanh', 'Vội', 'Trừu tượng', 2),
('Chậm', 'Trễ', 'Trừu tượng', 2),
('Mới', 'Lạ', 'Trừu tượng', 1),
('Cũ', 'Cổ', 'Trừu tượng', 1),
('Dễ', 'Đơn giản', 'Trừu tượng', 1),
('Thông minh', 'Sáng tạo', 'Trừu tượng', 2),
('Thành công', 'Thành tựu', 'Trừu tượng', 2);

-- Category: Hành động (51 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Hẹn hò', 'Tán tỉnh', 'Hành động', 3),
('Đi bộ', 'Chạy bộ', 'Hành động', 2),
('Ngủ', 'Nghỉ ngơi', 'Hành động', 2),
('Ăn', 'Dùng bữa', 'Hành động', 1),
('Học', 'Làm bài', 'Hành động', 2),
('Chơi game', 'Giải trí', 'Hành động', 2),
('Đọc sách', 'Đọc báo', 'Hành động', 2),
('Nấu ăn', 'Chuẩn bị đồ ăn', 'Hành động', 2),
('Dọn dẹp', 'Vệ sinh', 'Hành động', 2),
('Đánh răng', 'Vệ sinh răng', 'Hành động', 1),
('Đi xe', 'Lái xe', 'Hành động', 2),
('Chạy', 'Tập thể dục', 'Hành động', 2),
('Nhảy', 'Khiêu vũ', 'Hành động', 2),
('Chơi nhạc', 'Chơi đàn', 'Hành động', 2),
('Vẽ', 'Tô màu', 'Hành động', 2),
('Viết', 'Ghi chép', 'Hành động', 2),
('Đọc', 'Lướt đọc', 'Hành động', 1),
('Nghe', 'Lắng nghe', 'Hành động', 2),
('Nói', 'Phát biểu', 'Hành động', 2),
('Hỏi', 'Thắc mắc', 'Hành động', 2),
('Giải thích', 'Làm rõ', 'Hành động', 2),
('Thảo luận', 'Bàn luận', 'Hành động', 2),
('Hòa giải', 'Giải quyết', 'Hành động', 2),
('Thỏa thuận', 'Đồng ý', 'Hành động', 2),
('Từ bỏ', 'Bỏ cuộc', 'Hành động', 2),
('Tiếp tục', 'Duy trì', 'Hành động', 2),
('Bắt đầu', 'Khởi động', 'Hành động', 2),
('Kết thúc', 'Hoàn thành', 'Hành động', 2),
('Làm việc', 'Lao động', 'Hành động', 2),
('Học tập', 'Nghiên cứu', 'Hành động', 2),
('Du lịch', 'Đi chơi', 'Hành động', 2),
('Ngáp', 'Hắt hơi', 'Hành động', 1),
('Cười', 'Mỉm cười', 'Hành động', 1),
('La hét', 'Hò hét', 'Hành động', 2),
('Ôm', 'Hôn', 'Hành động', 1),
('Nằm', 'Ngồi', 'Hành động', 1),
('Đứng', 'Quỳ', 'Hành động', 1),
('Tắm', 'Gội đầu', 'Hành động', 1),
('Mặc đồ', 'Trang điểm', 'Hành động', 2),
('Hát', 'Đọc rap', 'Hành động', 2),
('Trả lời', 'Phản biện', 'Hành động', 3),
('Tranh cãi', 'Thảo luận', 'Hành động', 2),
('Từ chối', 'Khước từ', 'Hành động', 2),
('Dừng lại', 'Quay lại', 'Hành động', 2),
('Thăm hỏi', 'Thăm nom', 'Hành động', 2),
('Gặp gỡ', 'Hẹn hò', 'Hành động', 2),
('Chia tay', 'Ly hôn', 'Hành động', 3),
('Cấu', 'Tát', 'Hành động', 2),
('Nói chuyện', 'Phỏng vấn', 'Hành động', 2),
('Đi bộ', 'Leo cầu thang', 'Hành động', 2),
('Ngủ', 'Chợp mắt', 'Hành động', 2);

-- Category: Động vật (54 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Chó', 'Mèo', 'Động vật', 1),
('Bò', 'Trâu', 'Động vật', 2),
('Ngựa', 'Lừa', 'Động vật', 2),
('Dê', 'Cừu', 'Động vật', 2),
('Thỏ', 'Chuột', 'Động vật', 2),
('Tôm', 'Cua', 'Động vật', 2),
('Sư tử', 'Hổ', 'Động vật', 2),
('Gấu', 'Báo', 'Động vật', 2),
('Voi', 'Hươu', 'Động vật', 2),
('Khỉ', 'Vượn', 'Động vật', 2),
('Rắn', 'Trăn', 'Động vật', 2),
('Cá sấu', 'Rùa', 'Động vật', 2),
('Chim cánh cụt', 'Chim hải âu', 'Động vật', 2),
('Cá heo', 'Cá voi', 'Động vật', 2),
('Bướm', 'Ong', 'Động vật', 2),
('Kiến', 'Mối', 'Động vật', 2),
('Nhện', 'Bọ cạp', 'Động vật', 2),
('Gián', 'Muỗi', 'Động vật', 2),
('Chim sẻ', 'Chim bồ câu', 'Động vật', 2),
('Chim đại bàng', 'Chim ưng', 'Động vật', 2),
('Nhím', 'Chuột chũi', 'Động vật', 2),
('Hà mã', 'Tê giác', 'Động vật', 2),
('Sao biển', 'Cầu gai', 'Động vật', 2),
('Hải cẩu', 'Sư tử biển', 'Động vật', 2),
('Đại bàng', 'Kền kền', 'Động vật', 2),
('Cú mèo', 'Diều hâu', 'Động vật', 2),
('Bồ nông', 'Hạc', 'Động vật', 2),
('Thiên nga', 'Ngỗng trời', 'Động vật', 2),
('Rái cá', 'Hải ly', 'Động vật', 2),
('Chồn', 'Cầy hương', 'Động vật', 2),
('Dơi', 'Cáo bay', 'Động vật', 1),
('Cá voi xanh', 'Cá nhà táng', 'Động vật', 2),
('Cá kiếm', 'Cá ngừ', 'Động vật', 2),
('Tôm hùm', 'Cua hoàng đế', 'Động vật', 2),
('Ốc', 'Sò', 'Động vật', 1),
('Hến', 'Trai', 'Động vật', 2),
('Ve sầu', 'Dế', 'Động vật', 2),
('Bọ ngựa', 'Châu chấu', 'Động vật', 2),
('Chuồn chuồn', 'Bướm đêm', 'Động vật', 2),
('Rết', 'Cuốn chiếu', 'Động vật', 2),
('Bọ hung', 'Bọ cánh cứng', 'Động vật', 2),
('Ếch', 'Cóc', 'Động vật', 1),
('Nhái', 'Ễnh ương', 'Động vật', 2),
('Thằn lằn', 'Tắc kè', 'Động vật', 2),
('Kỳ đà', 'Kỳ nhông', 'Động vật', 2),
('Công', 'Chim trĩ', 'Động vật', 2),
('Sói', 'Cáo', 'Động vật', 2),
('Hươu cao cổ', 'Hươu sao', 'Động vật', 2),
('Lợn', 'Lợn rừng', 'Động vật', 2),
('Vịt', 'Ngan', 'Động vật', 2),
('Sứa', 'Mực', 'Động vật', 2),
('Cá sấu', 'Thằn lằn', 'Động vật', 2),
('Hổ', 'Báo', 'Động vật', 2),
('Sư tử', 'Báo sư tử', 'Động vật', 3);

-- Category: Cơ thể (50 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Đầu', 'Não', 'Cơ thể', 2),
('Mắt', 'Mũi', 'Cơ thể', 1),
('Miệng', 'Môi', 'Cơ thể', 2),
('Răng', 'Lưỡi', 'Cơ thể', 2),
('Tay', 'Chân', 'Cơ thể', 1),
('Ngón tay', 'Ngón chân', 'Cơ thể', 2),
('Cổ', 'Vai', 'Cơ thể', 2),
('Lưng', 'Ngực', 'Cơ thể', 2),
('Tim', 'Phổi', 'Cơ thể', 2),
('Gan', 'Thận', 'Cơ thể', 2),
('Xương', 'Cơ', 'Cơ thể', 2),
('Da', 'Tóc', 'Cơ thể', 1),
('Móng tay', 'Móng chân', 'Cơ thể', 2),
('Lông mày', 'Lông mi', 'Cơ thể', 2),
('Má', 'Cằm', 'Cơ thể', 2),
('Trán', 'Thái dương', 'Cơ thể', 2),
('Cổ họng', 'Thanh quản', 'Cơ thể', 2),
('Đau bụng', 'Đau dạ dày', 'Cơ thể', 2),
('Sốt', 'Cảm', 'Cơ thể', 2),
('Ho', 'Sổ mũi', 'Cơ thể', 2),
('Khỏe mạnh', 'Cường tráng', 'Cơ thể', 2),
('Ốm yếu', 'Bệnh tật', 'Cơ thể', 2),
('Bác sĩ', 'Y tá', 'Cơ thể', 2),
('Khám bệnh', 'Điều trị', 'Cơ thể', 2),
('Tiêm', 'Uống thuốc', 'Cơ thể', 2),
('Băng bó', 'Băng gạc', 'Cơ thể', 2),
('Vết thương', 'Vết cắt', 'Cơ thể', 2),
('Máu', 'Huyết', 'Cơ thể', 1),
('Nhịp tim', 'Huyết áp', 'Cơ thể', 2),
('Hô hấp', 'Thở', 'Cơ thể', 2),
('Tiêu hóa', 'Hấp thụ', 'Cơ thể', 2),
('Miễn dịch', 'Kháng thể', 'Cơ thể', 2),
('Dị ứng', 'Mẫn cảm', 'Cơ thể', 2),
('Viêm', 'Sưng', 'Cơ thể', 2),
('Nhiễm trùng', 'Nhiễm khuẩn', 'Cơ thể', 2),
('Vaccine', 'Tiêm chủng', 'Cơ thể', 2),
('Phòng ngừa', 'Phòng bệnh', 'Cơ thể', 2),
('Ruột', 'Dạ dày', 'Cơ thể', 2),
('Mật', 'Tụy', 'Cơ thể', 3),
('Tử cung', 'Buồng trứng', 'Cơ thể', 3),
('Tinh hoàn', 'Tuyến tiền liệt', 'Cơ thể', 3),
('Huyết tương', 'Huyết cầu', 'Cơ thể', 3),
('Bạch cầu', 'Hồng cầu', 'Cơ thể', 2),
('Tiểu cầu', 'Huyết sắc tố', 'Cơ thể', 3),
('Đau đầu', 'Chóng mặt', 'Cơ thể', 2),
('Thuốc tây', 'Thuốc nam', 'Cơ thể', 2),
('Hồi phục', 'Bình phục', 'Cơ thể', 2),
('Khỏi bệnh', 'Lành bệnh', 'Cơ thể', 3),
('Phẫu thuật', 'Tiểu phẫu', 'Cơ thể', 2),
('Châm cứu', 'Bấm huyệt', 'Cơ thể', 2);

-- Category: Màu sắc (46 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Đỏ', 'Hồng', 'Màu sắc', 2),
('Xanh', 'Tím', 'Màu sắc', 2),
('Vàng', 'Cam', 'Màu sắc', 2),
('Trắng', 'Xám', 'Màu sắc', 2),
('Đen', 'Nâu', 'Màu sắc', 2),
('Xanh lá', 'Xanh dương', 'Màu sắc', 2),
('Đỏ đậm', 'Đỏ nhạt', 'Màu sắc', 2),
('Xanh đậm', 'Xanh nhạt', 'Màu sắc', 2),
('Vàng đậm', 'Vàng nhạt', 'Màu sắc', 2),
('Hồng đậm', 'Hồng nhạt', 'Màu sắc', 2),
('Tím đậm', 'Tím nhạt', 'Màu sắc', 2),
('Cam đậm', 'Cam nhạt', 'Màu sắc', 2),
('Nâu đậm', 'Nâu nhạt', 'Màu sắc', 2),
('Xám đậm', 'Xám nhạt', 'Màu sắc', 2),
('Đục', 'Mờ', 'Màu sắc', 1),
('Màu trung tính', 'Màu trung hòa', 'Màu sắc', 1),
('Pastel', 'Màu phấn', 'Màu sắc', 1),
('Neon', 'Huỳnh quang', 'Màu sắc', 1),
('Metallic', 'Ánh kim', 'Màu sắc', 1),
('Gradient', 'Loang màu', 'Màu sắc', 1),
('Monochrome', 'Độc sắc', 'Màu sắc', 1),
('Rainbow', 'Ngũ sắc', 'Màu sắc', 1),
('Ivory', 'Ngà voi', 'Màu sắc', 2),
('Turquoise', 'Ngọc lam', 'Màu sắc', 2),
('Magenta', 'Đỏ tía', 'Màu sắc', 2),
('Cyan', 'Xanh lơ', 'Màu sắc', 2),
('Maroon', 'Nâu đỏ', 'Màu sắc', 2),
('Olive', 'Ô liu', 'Màu sắc', 2),
('Salmon', 'Hồng cam', 'Màu sắc', 2),
('Lavender', 'Oải hương', 'Màu sắc', 2),
('Màu da', 'Màu nude', 'Màu sắc', 2),
('Màu đất', 'Màu gạch', 'Màu sắc', 2),
('Màu rêu', 'Màu cỏ úa', 'Màu sắc', 2),
('Màu khói', 'Màu ghi', 'Màu sắc', 2),
('Màu bạc', 'Màu xám', 'Màu sắc', 2),
('Màu đồng', 'Màu vàng đồng', 'Màu sắc', 2),
('Màu than', 'Màu chì', 'Màu sắc', 2),
('Màu mận', 'Màu bordeaux', 'Màu sắc', 2),
('Màu chàm', 'Màu lam', 'Màu sắc', 2),
('Màu kem', 'Màu sữa', 'Màu sắc', 2),
('Dạ quang', 'Phản quang', 'Màu sắc', 2),
('Trong suốt', 'Bán trong suốt', 'Màu sắc', 3),
('Màu nóng', 'Màu sặc sỡ', 'Màu sắc', 2),
('Màu lạnh', 'Tông lạnh', 'Màu sắc', 2),
('Đen', 'Xám tro', 'Màu sắc', 2),
('Trắng', 'Kem', 'Màu sắc', 2);

-- Category: Cảm xúc (49 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Yêu', 'Thích', 'Cảm xúc', 3),
('Ghen', 'Đố kỵ', 'Cảm xúc', 3),
('Vui', 'Hạnh phúc', 'Cảm xúc', 2),
('Buồn', 'Thất vọng', 'Cảm xúc', 2),
('Tức giận', 'Bực bội', 'Cảm xúc', 2),
('Lo lắng', 'Bồn chồn', 'Cảm xúc', 3),
('Tự tin', 'Tin tưởng', 'Cảm xúc', 3),
('Nhớ', 'Thương', 'Cảm xúc', 3),
('Hồi hộp', 'Lo âu', 'Cảm xúc', 3),
('Đau khổ', 'Buồn bã', 'Cảm xúc', 2),
('Tự hào', 'Kiêu hãnh', 'Cảm xúc', 3),
('Chán nản', 'Nản lòng', 'Cảm xúc', 2),
('Bình tĩnh', 'Thư thái', 'Cảm xúc', 2),
('Căng thẳng', 'Áp lực', 'Cảm xúc', 2),
('Thương hại', 'Xót thương', 'Cảm xúc', 3),
('Tha thứ', 'Bỏ qua', 'Cảm xúc', 2),
('Oán giận', 'Thù hận', 'Cảm xúc', 2),
('Yêu thương', 'Quý mến', 'Cảm xúc', 2),
('Ghét bỏ', 'Không thích', 'Cảm xúc', 2),
('Hy vọng', 'Mong đợi', 'Cảm xúc', 2),
('Lạc quan', 'Tích cực', 'Cảm xúc', 2),
('Bi quan', 'Tiêu cực', 'Cảm xúc', 2),
('Đau đớn', 'Khổ sở', 'Cảm xúc', 2),
('Tuyệt vời', 'Hoàn hảo', 'Cảm xúc', 2),
('Tồi tệ', 'Kinh khủng', 'Cảm xúc', 2),
('Mê', 'Nghiện', 'Cảm xúc', 1),
('Ghét', 'Căm', 'Cảm xúc', 2),
('Có lỗi', 'Ân hận', 'Cảm xúc', 2),
('Hối hận', 'Tiếc nuối', 'Cảm xúc', 2),
('Ngạc nhiên', 'Bất ngờ', 'Cảm xúc', 2),
('Xấu hổ', 'Tự ti', 'Cảm xúc', 2),
('Thích thú', 'Tò mò', 'Cảm xúc', 2),
('Phấn khích', 'Hồi hộp', 'Cảm xúc', 2),
('Thoải mái', 'Dễ chịu', 'Cảm xúc', 2),
('Khó chịu', 'Bực dọc', 'Cảm xúc', 2),
('Hài lòng', 'Thỏa mãn', 'Cảm xúc', 2),
('Bất mãn', 'Không hài lòng', 'Cảm xúc', 2),
('Biết ơn', 'Cảm kích', 'Cảm xúc', 3),
('Kính trọng', 'Tôn trọng', 'Cảm xúc', 3),
('Khinh thường', 'Coi thường', 'Cảm xúc', 3),
('Ngưỡng mộ', 'Thán phục', 'Cảm xúc', 3),
('Tuyệt vọng', 'Buông xuôi', 'Cảm xúc', 2),
('Bối rối', 'Hoảng loạn', 'Cảm xúc', 2),
('Ngại ngùng', 'Giữ kẽ', 'Cảm xúc', 2),
('Phấn khởi', 'Lạc quan', 'Cảm xúc', 2),
('Chán', 'Ngán', 'Cảm xúc', 1),
('Thù', 'Giận', 'Cảm xúc', 1),
('Cô đơn', 'Lẻ loi', 'Cảm xúc', 2),
('Vui sướng', 'Hả hê', 'Cảm xúc', 2);

-- Category: Ẩm thực (54 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Trà sữa', 'Trà đào', 'Ẩm thực', 2),
('Cà phê', 'Cà phê sữa', 'Ẩm thực', 2),
('Bánh mì', 'Bánh bao', 'Ẩm thực', 2),
('Phở', 'Bún bò', 'Ẩm thực', 2),
('Gỏi cuốn', 'Chả giò', 'Ẩm thực', 3),
('Bánh xèo', 'Bánh khọt', 'Ẩm thực', 3),
('Nước mắm', 'Nước tương', 'Ẩm thực', 2),
('Cơm', 'Xôi', 'Ẩm thực', 2),
('Chè', 'Sữa chua', 'Ẩm thực', 2),
('Bánh chưng', 'Bánh tét', 'Ẩm thực', 3),
('Nem', 'Chả', 'Ẩm thực', 2),
('Cháo', 'Súp', 'Ẩm thực', 2),
('Nước ngọt', 'Nước ép', 'Ẩm thực', 2),
('Bia', 'Rượu', 'Ẩm thực', 2),
('Sữa', 'Sữa đậu nành', 'Ẩm thực', 2),
('Kẹo', 'Socola', 'Ẩm thực', 2),
('Bánh mì kẹp', 'Bánh mì sandwich', 'Ẩm thực', 1),
('Sushi', 'Cơm cuộn', 'Ẩm thực', 2),
('Salad', 'Gỏi', 'Ẩm thực', 2),
('Steak', 'Thịt bò', 'Ẩm thực', 2),
('Bún riêu', 'Bún ốc', 'Ẩm thực', 2),
('Bún chả', 'Bún thịt nướng', 'Ẩm thực', 2),
('Cơm tấm', 'Cơm sườn', 'Ẩm thực', 2),
('Cháo lòng', 'Cháo gà', 'Ẩm thực', 2),
('Lẩu', 'Lẩu cay', 'Ẩm thực', 1),
('Rượu vang', 'Champagne', 'Ẩm thực', 2),
('Trà đá', 'Nhân trần', 'Ẩm thực', 2),
('Bánh tráng trộn', 'Bánh tráng nướng', 'Ẩm thực', 2),
('Xoài lắc', 'Cóc lắc', 'Ẩm thực', 2),
('Bò khô', 'Khô gà', 'Ẩm thực', 2),
('Mực rim', 'Cá rim', 'Ẩm thực', 2),
('Bánh cuốn', 'Bánh ướt', 'Ẩm thực', 2),
('Nem chua', 'Chả lụa', 'Ẩm thực', 2),
('Gà rán', 'Gà luộc', 'Ẩm thực', 2),
('Cá kho', 'Cá hấp', 'Ẩm thực', 2),
('Thịt kho', 'Thịt luộc', 'Ẩm thực', 2),
('Mì Ý', 'Nui', 'Ẩm thực', 2),
('Trứng ốp la', 'Trứng luộc', 'Ẩm thực', 2),
('Phô mai', 'Bơ', 'Ẩm thực', 2),
('Đường', 'Mật ong', 'Ẩm thực', 2),
('Muối', 'Nước mắm', 'Ẩm thực', 2),
('Tiêu', 'Ớt', 'Ẩm thực', 2),
('Tỏi', 'Hành tím', 'Ẩm thực', 2),
('Hành tây', 'Hành ta', 'Ẩm thực', 2),
('Cà chua', 'Dưa leo', 'Ẩm thực', 2),
('Khoai tây', 'Khoai lang', 'Ẩm thực', 2),
('Cà rốt', 'Củ cải trắng', 'Ẩm thực', 2),
('Chuối', 'Táo', 'Ẩm thực', 1),
('Bánh quy', 'Bánh xốp', 'Ẩm thực', 2),
('Mì tôm', 'Phở gói', 'Ẩm thực', 2),
('Bánh kem', 'Bánh bông lan', 'Ẩm thực', 2),
('Buffet', 'Gọi món', 'Ẩm thực', 2),
('Lẩu thái', 'Lẩu hải sản', 'Ẩm thực', 2),
('Nướng BBQ', 'Nướng ngói', 'Ẩm thực', 2);

-- Category: Địa điểm (53 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Nhà', 'Căn hộ', 'Địa điểm', 2),
('Trường học', 'Đại học', 'Địa điểm', 2),
('Bệnh viện', 'Phòng khám', 'Địa điểm', 2),
('Siêu thị', 'Cửa hàng', 'Địa điểm', 2),
('Nhà hàng', 'Quán ăn', 'Địa điểm', 2),
('Công viên', 'Sân chơi', 'Địa điểm', 2),
('Bãi biển', 'Bờ biển', 'Địa điểm', 2),
('Rạp chiếu phim', 'Rạp hát', 'Địa điểm', 2),
('Sân bay', 'Ga tàu', 'Địa điểm', 2),
('Thành phố', 'Thị trấn', 'Địa điểm', 2),
('Quán cà phê', 'Quán trà', 'Địa điểm', 2),
('Thư viện', 'Phòng đọc', 'Địa điểm', 2),
('Bảo tàng', 'Phòng trưng bày', 'Địa điểm', 2),
('Nhà ga', 'Bến xe', 'Địa điểm', 2),
('Bến tàu', 'Cảng', 'Địa điểm', 2),
('Quán bar', 'Quán rượu', 'Địa điểm', 2),
('Khách sạn', 'Nhà nghỉ', 'Địa điểm', 2),
('Trung tâm mua sắm', 'Chợ', 'Địa điểm', 2),
('Ngân hàng', 'Quỹ tín dụng', 'Địa điểm', 2),
('Trạm dừng', 'Bến xe buýt', 'Địa điểm', 2),
('Trường mẫu giáo', 'Trường tiểu học', 'Địa điểm', 2),
('Trường cấp 2', 'Trường cấp 3', 'Địa điểm', 2),
('Sân thượng', 'Ban công', 'Địa điểm', 2),
('Sân sau', 'Vườn sau', 'Địa điểm', 2),
('Hành lang', 'Lối đi', 'Địa điểm', 2),
('Cầu thang', 'Thang máy', 'Địa điểm', 2),
('Tòa án', 'Viện kiểm sát', 'Địa điểm', 2),
('Ủy ban', 'Cơ quan', 'Địa điểm', 2),
('Lăng tẩm', 'Đền đài', 'Địa điểm', 2),
('Chùa', 'Đình', 'Địa điểm', 2),
('Tu viện', 'Thiền viện', 'Địa điểm', 2),
('Rừng', 'Núi', 'Địa điểm', 1),
('Công viên', 'Vườn hoa', 'Địa điểm', 2),
('Sân vận động', 'Nhà thi đấu', 'Địa điểm', 2),
('Phòng gym', 'Sân tập', 'Địa điểm', 2),
('Bưu điện', 'Điểm giao dịch', 'Địa điểm', 2),
('Trạm xăng', 'Trạm thu phí', 'Địa điểm', 2),
('Phòng học', 'Thư viện', 'Địa điểm', 2),
('Phòng thí nghiệm', 'Phòng mổ', 'Địa điểm', 3),
('Phòng họp', 'Hội trường', 'Địa điểm', 2),
('Văn phòng', 'Phòng làm việc', 'Địa điểm', 1),
('Nhà xưởng', 'Nhà máy', 'Địa điểm', 2),
('Kho', 'Hầm', 'Địa điểm', 2),
('Garage', 'Bãi xe', 'Địa điểm', 2),
('Lối vào', 'Cổng', 'Địa điểm', 1),
('Lối ra', 'Thoát hiểm', 'Địa điểm', 2),
('Tầng 1', 'Tầng trệt', 'Địa điểm', 2),
('Tầng thượng', 'Gác mái', 'Địa điểm', 2),
('Tầng hầm', 'Hầm để xe', 'Địa điểm', 3),
('Nhà tù', 'Trại giam', 'Địa điểm', 3),
('Đồn cảnh sát', 'Tòa án', 'Địa điểm', 2),
('Nhà thờ', 'Chùa', 'Địa điểm', 2),
('Sở thú', 'Rạp xiếc', 'Địa điểm', 2);

-- Category: Thể thao (45 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Bóng đá', 'Bóng rổ', 'Thể thao', 2),
('Bóng chuyền', 'Bóng bàn', 'Thể thao', 2),
('Cầu lông', 'Tennis', 'Thể thao', 2),
('Ném', 'Ném bóng', 'Thể thao', 2),
('Đá', 'Đá bóng', 'Thể thao', 1),
('Đánh', 'Đánh bóng', 'Thể thao', 1),
('Bắt', 'Bắt bóng', 'Thể thao', 1),
('Bắn', 'Bắn cung', 'Thể thao', 2),
('Leo', 'Leo núi', 'Thể thao', 2),
('Lặn', 'Lặn biển', 'Thể thao', 2),
('Lướt', 'Lướt sóng', 'Thể thao', 2),
('Trượt', 'Trượt tuyết', 'Thể thao', 2),
('Đua', 'Đua xe', 'Thể thao', 2),
('Vận động viên', 'Cầu thủ', 'Thể thao', 2),
('Trọng tài', 'Huấn luyện viên', 'Thể thao', 2),
('Sân thi đấu', 'Sân tập', 'Thể thao', 2),
('Giải đấu', 'Cuộc thi', 'Thể thao', 2),
('Trận đấu', 'Trận thi đấu', 'Thể thao', 2),
('Thắng', 'Chiến thắng', 'Thể thao', 1),
('Ghi bàn', 'Ghi điểm', 'Thể thao', 2),
('Bàn thắng', 'Điểm số', 'Thể thao', 2),
('Thẻ vàng', 'Thẻ phạt', 'Thể thao', 2),
('Thời gian', 'Thời lượng', 'Thể thao', 2),
('Vòng', 'Lượt', 'Thể thao', 2),
('Giải', 'Cúp', 'Thể thao', 2),
('Huy chương vàng', 'Huy chương bạc', 'Thể thao', 2),
('Kỷ lục', 'Thành tích', 'Thể thao', 2),
('Thể lực', 'Sức khỏe', 'Thể thao', 2),
('Golf', 'Khúc côn cầu', 'Thể thao', 2),
('Cờ vua', 'Cờ tướng', 'Thể thao', 2),
('Cờ vây', 'Cờ caro', 'Thể thao', 2),
('Đấu kiếm', 'Đấu vật', 'Thể thao', 2),
('Boxing', 'Quyền anh', 'Thể thao', 1),
('Muay Thái', 'Kickboxing', 'Thể thao', 2),
('Thể dục dụng cụ', 'Nhào lộn', 'Thể thao', 2),
('Trượt băng', 'Patin', 'Thể thao', 2),
('Đua ngựa', 'Đua chó', 'Thể thao', 2),
('Đua thuyền', 'Chèo thuyền', 'Thể thao', 2),
('Nhảy dù', 'Dù lượn', 'Thể thao', 2),
('Cắm trại', 'Dã ngoại', 'Thể thao', 2),
('Yoga', 'Thiền', 'Thể thao', 2),
('Phạm lỗi', 'Việt vị', 'Thể thao', 2),
('Tập luyện', 'Luyện tập', 'Thể thao', 2),
('Bóng đá', 'Bóng đá trong nhà', 'Thể thao', 2),
('Bơi', 'Lặn', 'Thể thao', 2);

-- Category: Công nghệ (7 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Phát trực tuyến', 'Xem trực tuyến', 'Công nghệ', 2),
('Bitcoin', 'Tiền điện tử', 'Công nghệ', 2),
('Màn hình', 'Máy chiếu', 'Công nghệ', 2),
('Pin', 'Ắc quy', 'Công nghệ', 1),
('Usb', 'Thẻ nhớ', 'Công nghệ', 1),
('Tin rác', 'Quảng cáo rác', 'Công nghệ', 2),
('Ví điện tử', 'Ví số', 'Công nghệ', 2);

-- Category: Thời gian (46 pairs)
INSERT INTO word_pairs (word_civilian, word_undercover, category, difficulty) VALUES
('Sáng', 'Trưa', 'Thời gian', 2),
('Chiều', 'Tối', 'Thời gian', 2),
('Hôm nay', 'Hôm qua', 'Thời gian', 2),
('Tuần', 'Tháng', 'Thời gian', 2),
('Năm', 'Thập kỷ', 'Thời gian', 2),
('Giờ', 'Phút', 'Thời gian', 1),
('Xuân', 'Hạ', 'Thời gian', 2),
('Thu', 'Đông', 'Thời gian', 2),
('Thứ Hai', 'Thứ Ba', 'Thời gian', 2),
('Thứ Tư', 'Thứ Năm', 'Thời gian', 2),
('Thứ Sáu', 'Thứ Bảy', 'Thời gian', 2),
('Quá khứ', 'Dĩ vãng', 'Thời gian', 2),
('Trước', 'Phía trước', 'Thời gian', 1),
('Sớm', 'Sớm hơn', 'Thời gian', 1),
('Luôn luôn', 'Thường xuyên', 'Thời gian', 2),
('Thỉnh thoảng', 'Hiếm khi', 'Thời gian', 2),
('Tạm thời', 'Nhất thời', 'Thời gian', 2),
('Ngắn hạn', 'Trước mắt', 'Thời gian', 2),
('Thế kỷ', 'Thiên niên kỷ', 'Thời gian', 2),
('Quý', 'Học kỳ', 'Thời gian', 2),
('Đầu tuần', 'Giữa tuần', 'Thời gian', 1),
('Mùa mưa', 'Mùa ẩm', 'Thời gian', 1),
('Mùa gặt', 'Mùa cấy', 'Thời gian', 2),
('Tết', 'Lễ', 'Thời gian', 1),
('Sinh nhật', 'Thôi nôi', 'Thời gian', 2),
('Giỗ', 'Kỵ nhật', 'Thời gian', 2),
('Đồng hồ', 'Lịch', 'Thời gian', 1),
('Noel', 'Tết Dương lịch', 'Thời gian', 2),
('Bình minh', 'Rạng đông', 'Thời gian', 1),
('Đêm', 'Tối', 'Thời gian', 1),
('Trưa', 'Chiều', 'Thời gian', 1),
('Mãi mãi', 'Lâu dài', 'Thời gian', 2),
('Mùa vụ', 'Thời vụ', 'Thời gian', 2),
('Sớm mai', 'Rạng sáng', 'Thời gian', 2),
('Tích tắc', 'Khoảnh khắc', 'Thời gian', 3),
('Vĩnh cửu', 'Bất tận', 'Thời gian', 3),
('Khoảnh khắc', 'Chốc lát', 'Thời gian', 2),
('Thời đại', 'Thế hệ', 'Thời gian', 2),
('Thanh xuân', 'Tuổi thơ', 'Thời gian', 2),
('Tuổi già', 'Xế chiều', 'Thời gian', 2),
('Tương lai', 'Viễn cảnh', 'Thời gian', 2),
('Hôm kia', 'Tuần trước', 'Thời gian', 2),
('Ngày mốt', 'Tuần sau', 'Thời gian', 2),
('Đám cưới', 'Đính hôn', 'Thời gian', 2),
('Đám ma', 'Giỗ đầu', 'Thời gian', 2),
('Đồng hồ', 'Đồng hồ đeo tay', 'Thời gian', 2);

-- Total: 508 word pairs
